### ISSUE TITLE
External dependencies not satisfied: linux-current release 215

### ISSUE THREAD

**Issue by lortfarquad** [infinitymdm/xone-solus#1]
![thx4yourwork](https://user-images.githubusercontent.com/113276785/189514171-2fd1174c-adad-44b7-a4a4-f11bc7d552df.jpg)

**Comment by infinitymdm** [comment]
Looks like I need to rebuild against the most recent kernel patch. Thanks for bringing this to my attention. I'll make sure to have that done by this afternoon.

**Comment by infinitymdm** [comment]
Just posted a new release: https://github.com/infinitymdm/xone-solus/releases/tag/v0.3-5.15.50-217
